<?php

return PhpCsFixer\Config::create()
    ->setIndent('    ')
    ->setLineEnding("\n")
    ->setRiskyAllowed(true)
    ->setRules([
        // PSR-1
        'encoding'         => true,
        'full_opening_tag' => true,
        // PSR-2
        'blank_line_after_namespace' => true,
        'braces'                     => true,
        'class_definition'           => true,
        'elseif'                     => true,
        'function_declaration'       => true,
        'indentation_type'           => true,
        'line_ending'                => true,
        'lowercase_constants'        => true,
        'lowercase_keywords'         => true,
        'method_argument_space'      => [
            'on_multiline' => 'ensure_fully_multiline',
        ],
        'no_break_comment'                   => true,
        'no_closing_tag'                     => true,
        'no_spaces_after_function_name'      => true,
        'no_spaces_inside_parenthesis'       => true,
        'no_trailing_whitespace'             => true,
        'no_trailing_whitespace_in_comment'  => true,
        'single_blank_line_at_eof'           => true,
        'single_class_element_per_statement' => [
            'elements' => [
                'property',
            ],
        ],
        'single_import_per_statement'    => true,
        'single_line_after_imports'      => true,
        'switch_case_semicolon_to_colon' => true,
        'switch_case_space'              => true,
        'visibility_required'            => true,
        // Custome rules
        'array_indentation'       => true,
        'array_syntax'            => ['syntax' => 'short'],
        'blank_line_before_return'                      => true,
        'binary_operator_spaces'  => [
            'default'   => 'single_space',
            'operators' => [
                '=>' => 'align_single_space_minimal',
            ],
        ],
        'cast_spaces'                 => ['space' => 'none'],
        'class_attributes_separation' => [
            'elements' => [
                'method',
            ],
        ],
        'combine_consecutive_issets'                    => true,
        'combine_consecutive_unsets'                    => true,
        'combine_nested_dirname'                        => true,
        'compact_nullable_typehint'                     => true,
        'concat_space'                                  => true,
        'declare_equal_normalize'                       => true,
        'dir_constant'                                  => true,
        'escape_implicit_backslashes'                   => true,
        'fopen_flag_order'                              => true,
        'fully_qualified_strict_types'                  => true,
        'function_to_constant'                          => true,
        'function_typehint_space'                       => true,
        'include'                                       => true,
        'list_syntax'                                   => ['syntax' => 'short'],
        'lowercase_cast'                                => true,
        'lowercase_static_reference'                    => true,
        'magic_constant_casing'                         => true,
        'magic_method_casing'                           => true,
        'method_chaining_indentation'                   => true,
        'modernize_types_casting'                       => true,
        'multiline_whitespace_before_semicolons'        => true,
        'native_function_casing'                        => true,
        'native_function_type_declaration_casing'       => true,
        'new_with_braces'                               => true,
        'no_alias_functions'                            => true,
        'no_alternative_syntax'                         => true,
        'no_blank_lines_after_class_opening'            => true,
        'no_blank_lines_after_phpdoc'                   => true,
        'no_empty_comment'                              => true,
        'no_empty_phpdoc'                               => true,
        'no_empty_statement'                            => true,
        'no_extra_blank_lines'                          => true,
        'no_leading_import_slash'                       => true,
        'no_leading_namespace_whitespace'               => true,
        'no_mixed_echo_print'                           => ['use' => 'echo'],
        'no_multiline_whitespace_around_double_arrow'   => true,
        'no_null_property_initialization'               => true,
        'normalize_index_brace'                         => true,
        'no_short_bool_cast'                            => true,
        'no_singleline_whitespace_before_semicolons'    => true,
        'no_spaces_around_offset'                       => true,
        'no_superfluous_elseif'                         => true,
        'no_trailing_comma_in_singleline_array'         => true,
        'no_unneeded_control_parentheses'               => true,
        'no_unneeded_curly_braces'                      => true,
        'no_unneeded_final_method'                      => true,
        'no_unused_imports'                             => true,
        'no_useless_else'                               => true,
        'no_useless_return'                             => true,
        'no_whitespace_before_comma_in_array'           => true,
        'no_whitespace_in_blank_line'                   => true,
        'object_operator_without_whitespace'            => true,
        'phpdoc_align'                                  => true,
        'phpdoc_annotation_without_dot'                 => true,
        'phpdoc_indent'                                 => true,
        'phpdoc_inline_tag'                             => true,
        'phpdoc_no_access'                              => true,
        'phpdoc_no_alias_tag'                           => true,
        'phpdoc_no_empty_return'                        => true,
        'phpdoc_no_package'                             => true,
        'phpdoc_no_useless_inheritdoc'                  => true,
        'phpdoc_order'                                  => true,
        'phpdoc_return_self_reference'                  => true,
        'phpdoc_scalar'                                 => true,
        'phpdoc_separation'                             => true,
        'phpdoc_single_line_var_spacing'                => true,
        'phpdoc_summary'                                => true,
        'phpdoc_to_comment'                             => true,
        'phpdoc_trim_consecutive_blank_line_separation' => true,
        'phpdoc_trim'                                   => true,
        'phpdoc_types_order'                            => ['null_adjustment' => 'always_last'],
        'phpdoc_types'                                  => true,
        'phpdoc_var_annotation_correct_order'           => true,
        'phpdoc_var_without_name'                       => true,
        'return_type_declaration'                       => true,
        'semicolon_after_instruction'                   => true,
        'short_scalar_cast'                             => true,
        'single_quote'                                  => false,
        'space_after_semicolon'                         => ['remove_in_empty_for_expressions' => true],
        'standardize_not_equals'                        => true,
        'ternary_operator_spaces'                       => true,
        'ternary_to_null_coalescing'                    => true,
        'trailing_comma_in_multiline_array'             => true,
        'trim_array_spaces'                             => true,
        'unary_operator_spaces'                         => true,
        'whitespace_after_comma_in_array'               => true,
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->files()
            ->exclude('vendor')
            ->in(__DIR__)
            ->name('*.php')
    );
